name: dog_marker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0-65.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  riverpod_annotation: ^2.3.1
  hooks_riverpod:
  flutter_hooks:
  image_picker: ^1.0.4
  file_selector: ^1.0.1
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  uuid: ^4.0.0
  geolocator: ^10.1.0
  json_serializable: ^6.7.1
  flutter_expandable_fab: ^2.0.0
  flutter_map: any
  cached_network_image: ^3.3.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.4
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

analyzer:
  plugins:
    - custom_lint